import os
import json
import random
import spacy
from spacy.training.example import Example
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ACTIVE_LEARNING_PATH = os.path.join(BASE_DIR, "data", "active_learning_pool.json")
MODEL_DIR = os.path.join(BASE_DIR, "models", "kapuletu_ai_v1")

def run_continuous_training():
    """
    Continuous Training Job.
    
    This script is designed to be run via a CRON job or Celery worker (e.g. nightly).
    It checks for new ground-truth data generated by Treasurers, loads the current 
    production AI model, and fine-tunes it on the new data to prevent concept drift.
    """
    logger.info("KapuLetu AI: Starting Continuous Learning Cycle...")
    
    if not os.path.exists(ACTIVE_LEARNING_PATH):
        logger.info("No new active learning data found. Sleeping.")
        return
        
    with open(ACTIVE_LEARNING_PATH, "r", encoding="utf-8") as f:
        pool_data = json.load(f)
        
    if len(pool_data) < 50:
        logger.info(f"Only {len(pool_data)} samples in the pool. Waiting for at least 50 to prevent overfitting.")
        return

    logger.info(f"Found {len(pool_data)} new human-verified samples. Initializing fine-tuning.")
    
    # 1. Load the existing production model
    if not os.path.exists(MODEL_DIR):
        logger.error(f"Cannot perform continuous learning: Base model not found at {MODEL_DIR}")
        return
        
    nlp = spacy.load(MODEL_DIR)
    
    # 2. Format the training examples
    examples = []
    for item in pool_data:
        text = item["text"]
        entities = item["entities"]
        
        doc = nlp.make_doc(text)
        try:
            example = Example.from_dict(doc, {"entities": entities})
            examples.append(example)
        except Exception as e:
            logger.warning(f"Failed to align active learning sample: {e}")
            continue

    if not examples:
        logger.error("No valid examples to train on.")
        return

    # 3. Fine-Tune the NER Pipe
    logger.info(f"Fine-tuning on {len(examples)} verified examples...")
    ner = nlp.get_pipe("ner")
    
    # We only update the NER pipe, disable others if any exist
    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]
    with nlp.disable_pipes(*other_pipes):
        optimizer = nlp.resume_training()
        
        # Run 3 light epochs for incremental learning (not a full retrain to avoid catastrophic forgetting)
        for epoch in range(3):
            random.shuffle(examples)
            losses = {}
            # Batch the examples
            from spacy.util import minibatch, compounding
            batches = minibatch(examples, size=compounding(4.0, 32.0, 1.001))
            for batch in batches:
                nlp.update(
                    batch,
                    drop=0.2, # Add slight dropout to generalize
                    losses=losses,
                    sgd=optimizer
                )
            logger.info(f"Incremental Epoch {epoch+1}/3 - Loss: {losses.get('ner', 0.0):.2f}")

    # 4. Save the updated model
    logger.info("Continuous Learning Complete. Saving updated weights to production...")
    nlp.to_disk(MODEL_DIR)
    
    # 5. Archive the old pool so we don't over-train on it next time
    os.rename(ACTIVE_LEARNING_PATH, ACTIVE_LEARNING_PATH.replace(".json", "_archived.json"))
    logger.info("Successfully deployed smarter AI. Active learning pool archived.")

if __name__ == "__main__":
    run_continuous_training()
